# Generated by Django 4.1 on 2023-03-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
